#!/usr/bin/env bash
# 检查本机 Agent Mail Hub；缺失时克隆 mcp_agent_mail、建 venv、生成 token、
# 写 client.env 并注册服务（systemd/launchd）。已存在可用 Hub 时直接复用。
#
# 幂等且可自愈：
# - 不覆盖人工维护/远程指向的 client.env（无本脚本标记的配置只报错不动手）；
# - 本脚本生成的 client.env 带标记，探活失败时重跑会保留 token、
#   重建仓库/venv 并重试服务注册启动。
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=install-paths.sh
source "$SCRIPT_DIR/install-paths.sh"

HUB_REPO="${AGENT_MAIL_HUB_REPO:-https://github.com/fyc0451/mcp_agent_mail.git}"
INSTALL_DIR="$SCRIPT_DIR"
REPO_DIR="${MCP_AGENT_MAIL_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/mcp_agent_mail}"
CLIENT_ENV="${AGENT_MAIL_CLIENT_ENV:-$HOME/.agent-mail/client.env}"
HUB_PORT="${AGENT_MAIL_HUB_PORT:-8765}"
CLIENT_ENV_MARKER="# generated by agent-cockpit install-agent-mail-hub.sh"

amh_pick_python() {
  # 显式 PYTHON_BIN 必须可用且 ≥3.12；否则在常见候选里自动挑选。
  local candidate
  if [[ -n "${PYTHON_BIN:-}" ]]; then
    if amh_py_ok "$PYTHON_BIN"; then return 0; fi
    echo "PYTHON_BIN 指定的解释器不可用或低于 3.12: $PYTHON_BIN" >&2
    return 1
  fi
  PYTHON_BIN=""
  for candidate in python3 python3.13 python3.12; do
    if amh_py_ok "$candidate"; then PYTHON_BIN="$candidate"; return 0; fi
  done
  echo "未找到 Python 3.12+（已尝试 python3/python3.13/python3.12），可用 PYTHON_BIN 指定。" >&2
  return 1
}

amh_py_ok() {
  command -v "$1" >/dev/null 2>&1 \
    && "$1" -c 'import sys; raise SystemExit(sys.version_info < (3, 12))' 2>/dev/null
}

amh_client_env_managed() {
  # 仅“本脚本生成 + loopback hub”的配置视为可自愈的本地托管配置。
  [[ -f "$CLIENT_ENV" ]] || return 1
  grep -qxF "$CLIENT_ENV_MARKER" "$CLIENT_ENV" 2>/dev/null || return 1
  ac_client_env_loopback_hub "$CLIENT_ENV" >/dev/null
}

amh_probe_hub() {
  # 依据 client.env 的 hub/token 做一次 MCP initialize 探活。
  [[ -f "$CLIENT_ENV" ]] || return 1
  local hub token
  hub="$(sed -n 's/^hub=//p' "$CLIENT_ENV" | tail -n 1)"
  token="$(sed -n 's/^token=//p' "$CLIENT_ENV" | tail -n 1)"
  [[ -n "$hub" ]] || return 1
  HUB_URL="$hub" HUB_TOKEN="$token" "$PYTHON_BIN" - <<'PY'
import json, os, sys, urllib.request
hub = os.environ.get("HUB_URL", "").rstrip("/")
token = os.environ.get("HUB_TOKEN", "")
if not hub:
    sys.exit(1)
payload = {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {
    "protocolVersion": "2025-03-26", "capabilities": {},
    "clientInfo": {"name": "install-probe", "version": "1.0"}}}
req = urllib.request.Request(
    f"{hub}/api/", data=json.dumps(payload).encode(),
    headers={"Content-Type": "application/json",
             "Accept": "application/json, text/event-stream",
             "Authorization": f"Bearer {token}"},
    method="POST")
try:
    with urllib.request.urlopen(req, timeout=5) as resp:
        sys.exit(0 if resp.status == 200 else 1)
except Exception:
    sys.exit(1)
PY
}

amh_port_busy() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltnH "sport = :$port" 2>/dev/null | grep -q . && return 0
  fi
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -tiTCP:"$port" -sTCP:LISTEN 2>/dev/null | grep -q . && return 0
  fi
  return 1
}

amh_ensure_repo_and_venv() {
  if [[ ! -d "$REPO_DIR/.git" ]]; then
    git clone "$HUB_REPO" "$REPO_DIR"
  fi
  if [[ ! -x "$REPO_DIR/.venv/bin/python" ]]; then
    "$PYTHON_BIN" -m venv "$REPO_DIR/.venv"
    if [[ -x "$REPO_DIR/.venv/bin/pip" ]]; then
      "$REPO_DIR/.venv/bin/pip" install --upgrade pip >/dev/null
    fi
  fi
  if ! "$REPO_DIR/.venv/bin/python" -c 'import mcp_agent_mail' 2>/dev/null; then
    if [[ -x "$REPO_DIR/.venv/bin/pip" ]]; then
      "$REPO_DIR/.venv/bin/pip" install -e "$REPO_DIR" >/dev/null
    else
      echo "警告: $REPO_DIR/.venv 缺少 pip，未安装 Hub 依赖。" >&2
    fi
  fi
}

amh_render_systemd_unit() {
  # amh_render_systemd_unit <unit_path> <install_dir> <repo_dir>
  local unit_path="$1" install_dir="$2" repo_dir="$3"
  local sys_install sys_exec repo_env_line=""
  sys_install="$(ac_escape_systemd_value "$install_dir")"
  sys_exec="$(ac_escape_systemd_exec_value "$install_dir")"
  sed \
    -e "s|__INSTALL_EXEC_DIR__|$(ac_escape_sed_replacement "$sys_exec")|g" \
    "$install_dir/agent-mail.service" > "$unit_path"
  if [[ "$repo_dir" != "${XDG_DATA_HOME:-$HOME/.local/share}/mcp_agent_mail" ]]; then
    repo_env_line="Environment=MCP_AGENT_MAIL_DIR=$(ac_escape_systemd_value "$repo_dir")"
    sed -i "/^Environment=PYTHONUNBUFFERED=1/a $(ac_escape_sed_replacement "$repo_env_line")" "$unit_path"
  fi
  chmod 600 "$unit_path"
}

amh_manual_instructions() {
  echo "手动启动命令（token 从 client.env 读取，勿外泄）："
  echo "  HTTP_HOST=127.0.0.1 HTTP_PORT=<client.env hub 的端口> \\"
  echo "  HTTP_BEARER_TOKEN=<client.env 的 token> \\"
  echo "  DATABASE_URL=sqlite+aiosqlite:///$REPO_DIR/storage.sqlite3 \\"
  echo "  $REPO_DIR/.venv/bin/python -m mcp_agent_mail.cli serve-http"
}

amh_register_service() {
  if command -v systemctl >/dev/null 2>&1 && systemctl --user daemon-reload 2>/dev/null; then
    local unit_dir="$HOME/.config/systemd/user"
    local unit_path="$unit_dir/agent-mail.service"
    mkdir -p "$unit_dir"
    amh_render_systemd_unit "$unit_path" "$INSTALL_DIR" "$REPO_DIR"
    systemctl --user daemon-reload
    # enable 设置开机自启；restart 确保加载最新 unit 并处于 active。
    systemctl --user enable agent-mail.service
    systemctl --user restart agent-mail.service
    echo "本地 Agent Mail Hub 服务已注册并启动: agent-mail.service"
    return 0
  fi
  if [[ "$(uname -s)" == "Darwin" ]] && command -v launchctl >/dev/null 2>&1; then
    "$INSTALL_DIR/agent-mail-launchd.sh" install
    return 0
  fi
  echo "警告: 未检测到可用的 systemd/launchd；配置与运行环境已生成，但服务未注册。" >&2
  return 1
}

amh_probe_loop() {
  # 服务启动后探活（最多 15 秒）。
  local _
  for _ in $(seq 1 15); do
    if amh_probe_hub; then
      echo "本地 Agent Mail Hub 就绪: $(sed -n 's/^hub=//p' "$CLIENT_ENV" | tail -n 1)"
      return 0
    fi
    sleep 1
  done
  echo "警告: Hub 服务已注册但 15 秒内探活未通过；请检查 agent-mail 服务日志后重跑本脚本。" >&2
  return 1
}

amh_main() {
  if [[ "${AGENT_MAIL_SKIP_HUB:-}" == "1" ]]; then
    echo "AGENT_MAIL_SKIP_HUB=1：跳过本地 Agent Mail Hub 检查与安装。"
    return 0
  fi

  amh_pick_python

  if amh_probe_hub; then
    echo "复用已有 Agent Mail Hub: $(sed -n 's/^hub=//p' "$CLIENT_ENV" | tail -n 1)"
    return 0
  fi

  if [[ -f "$CLIENT_ENV" ]] && ! amh_client_env_managed; then
    echo "警告: $CLIENT_ENV 已存在但其 Hub 探活失败（未运行/地址不可达/token 不符）。" >&2
    echo "该配置不是本脚本生成（或指向非 loopback Hub），不覆盖；请修复对应 Hub 或手工校正 client.env 后重跑。" >&2
    return 1
  fi

  ac_validate_install_dir "$INSTALL_DIR"
  ac_validate_install_dir "$REPO_DIR"

  if [[ -f "$CLIENT_ENV" ]]; then
    # 自愈路径：本脚本生成的配置探活失败——保留 token，补齐运行环境并重试注册启动。
    echo "检测到本脚本生成的本地 Hub 配置不可用，开始自愈（保留现有 token）。"
    amh_ensure_repo_and_venv
    if [[ "${AGENT_MAIL_NO_SERVICE:-}" == "1" ]]; then
      amh_manual_instructions
      return 0
    fi
    amh_register_service || return 1
    amh_probe_loop
    return $?
  fi

  echo "未发现可用的本地 Agent Mail Hub，开始安装到: $REPO_DIR"
  amh_ensure_repo_and_venv

  if amh_port_busy "$HUB_PORT"; then
    echo "端口 $HUB_PORT 已被占用且无可用 client.env；不启动托管 Hub。" >&2
    echo "请确认占用者是否为既有 Hub：若是，请把它写入 $CLIENT_ENV（hub=/token=）。" >&2
    return 1
  fi

  local token
  token="$("$PYTHON_BIN" -c 'import secrets; print(secrets.token_urlsafe(32))')"
  mkdir -p "$(dirname "$CLIENT_ENV")"
  umask 077
  cat > "$CLIENT_ENV" <<EOF
$CLIENT_ENV_MARKER
hub=http://127.0.0.1:$HUB_PORT
token=$token
EOF
  chmod 600 "$CLIENT_ENV"
  echo "已写入 Hub 客户端配置: $CLIENT_ENV（token 已生成，勿外泄）"

  if [[ "${AGENT_MAIL_NO_SERVICE:-}" == "1" ]]; then
    echo "AGENT_MAIL_NO_SERVICE=1：跳过服务注册。"
    amh_manual_instructions
    return 0
  fi
  amh_register_service || return 1
  amh_probe_loop
}

# 允许测试脚本 source 本文件复用函数；直接执行时才跑主流程。
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  amh_main "$@"
fi
